### ISSUE TITLE
https://qingjie.me/这个网站的配置能不能也搞一下

### ISSUE THREAD

**Issue by zcracker** [yourtion/SurgeConfigGenerator#2]
https://qingjie.me/这个网站的配置能不能也搞一下

**Comment by yourtion** [comment]
@ztechie 这个可以通过配置添加的。参考：https://github.com/yourtion/SurgeConfigGenerator/commit/630152726400862afcb7cebfdfad73c0a4e34077

我在 `config.sample.php` 添加了，其实很简单，在 `surge` 字段添加配置：

``` php
'surge' => array(
  'Abclite_ADB' => 'http://abclite.cn/Abclite_ADB.conf',
  'Abclite' => 'http://abclite.cn/Abclite.conf',
  'QingJie' => 'https://down.qingjie.me/surge/Group_rules.conf',
  'QingJieS' => 'https://down.qingjie.me/surge/Group_rules_s.conf'
),
```

请求时候类似这样：http://server.com/surge/?config=QingJie&account=Abclite1&passwd=myPassword
